### ISSUE TITLE
Would be interested to implement the Android version

### ISSUE THREAD

**Issue by yozef** [hansemannn/ti.paypal#1]
Hi Hans,

Any intention to unify the APIs with Android. I know there is an iOS & Android module here: https://github.com/appcelerator-modules/ti.paypal

However, as you may know it's not the native modal which opens on neither iOS or Android. 
If there is no native sdk for Android, I guess we can use the appcelerator-modules/ti.paypal for Android, if not, I'd be interested to pitch in on it.

**Comment by hansemannn** [comment]
Well...The "old" ti.paypal did use the native frameworks, but at that time, their SDK presented the views in a webview (which is the biggest change to the current SDK). There is an Android-SDK of the latest PayPal-SDK that has a very similar API to the iOS one. I hope someone is interested in the Android-part, so we may are able to replace the "official" one by time. Until then, I can only help with the iOS SDK.

**Comment by yozef** [comment]
... and the Android version is here : https://github.com/AppWerft/Ti.Paypal

**Comment by hansemannn** [comment]
Added a comment to the Android version of @appwerft, thanks!
