### ISSUE TITLE
Docs for setup

### ISSUE THREAD

**Issue by samueleastdev** [hansemannn/ti.paypal#4]
Hi,

Just wondering if there are any docs regarding setup with PayPal. I have setup a PayPal developer sandbox account and created a app called RealFitness.

I have also created a sandbox business pro account.

<img width="1239" alt="screen shot 2016-10-07 at 18 24 14" src="https://cloud.githubusercontent.com/assets/1894778/19199309/458f1a40-8cbb-11e6-856d-a5c64cd99a09.png">

I have copied the client id into the configuration setup.

```
var PayPal = require("ti.paypal");
PayPal.initialize({
    clientIdSandbox: "Ab4PHW18TUQY0K0C2Qmpc0o86BwxrcLzIp3n398lhbgXdGRU-(my client sandbox id)",
    clientIdProduction: "<YOUR_CLIENT_ID_PRODUCTION>",
    environment: PayPal.ENVIRONMENT_SANDBOX // or: ENVIRONMENT_PRODUCTION
});
```

But when i try and run the app it just stays on the following screen not sure if it take PayPal a while to setup, from working with PayPal in the past i have had this issue.

![img_1871](https://cloud.githubusercontent.com/assets/1894778/19199351/8bdd368a-8cbb-11e6-9b1c-8e35ef1fc63b.PNG)

Can you let me know where i am going wrong?

Thanks

**Comment by hansemannn** [comment]
Looks valid to me. I would add a link to [this page](https://developer.paypal.com/developer/applications/) but that's where you already are. Did you use the full example code provided? Maybe your ATS-settings block some requests or PayPal was down? Not many things that could break from the module-side there :-)

**Comment by samueleastdev** [comment]
Hi @hansemannn thanks for the response i created a new account and then a new app and its all working now ;)
