### ISSUE TITLE
Credit Card Payment

### ISSUE THREAD

**Issue by tav3lla** [hansemannn/ti.paypal#8]
Hi, 
with this module i can't use my credit card to pay.
Is there any way to do this?

thanks

**Comment by hansemannn** [comment]
You can simply set `acceptCreditCards: true` in the `createConfiguration` object. I need to document this better.

**Comment by tav3lla** [comment]
Thanks you.
Now i see the option "pay with credit card", but when i click on this option return an error and App crash.

[WARN] :   New layout set while view [object TiUIView] animating: Will relayout after animation.
[WARN] :   paymentDidCancel
[ERROR] :  The application has crashed with an uncaught exception 'NSInvalidArgumentException'.
[ERROR] :  Reason:
[ERROR] :  Application tried to present a nil modal view controller on target <PayPalPaymentViewController: 0x7fa4d3170600
[ERROR] :  Environment: sandbox
[ERROR] :  languageOrLocale: en
[ERROR] :  >
[ERROR] :  .
[ERROR] :  Stack trace:
[ERROR] :  0   CoreFoundation                      0x0000000111ed71ce __exceptionPreprocess + 270
[ERROR] :  1   libobjc.A.dylib                     0x0000000110fe0031 objc_exception_throw + 48
[ERROR] :  2   UIKit                               0x000000010d3cda20 -[UIViewController _presentViewController:withAnimationController:completion:] + 5142
[ERROR] :  3   UIKit                               0x000000010d3d02c6 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 99
[ERROR] :  4   UIKit                               0x000000010d3d0958 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
[ERROR] :  5   UIKit                               0x000000010d3d022c -[UIViewController _presentViewController:animated:completion:] + 169
[ERROR] :  6   UIKit                               0x000000010d3d0570 -[UIViewController presentViewController:animated:completion:] + 154
[ERROR] :  7   Ecoline Wash                        0x00000001097ced42 +[PPZebraCardIOWrapper presentCardIOPaymentViewControllerForNavigationController:forDelegate:] + 881
[ERROR] :  8   Ecoline Wash                        0x0000000109793388 -[PPSelectPaymentFlowManager selectPayMethodViewControllerUserDidSelectCreditCard:] + 68
[ERROR] :  9   Ecoline Wash                        0x00000001097964b1 -[PPSelectPayMethodViewController useCreditCard] + 105
[ERROR] :  10  Ecoline Wash                        0x00000001097de003 __50-[PPSelectPayMethodViewControllerIOS7 viewDidLoad]_block_invoke.53 + 34
[ERROR] :  11  Ecoline Wash                        0x0000000109784c2f -[PPPaymentMethodCell tableView:didSelectRowAtIndexPath:] + 202
[ERROR] :  12  Ecoline Wash                        0x00000001097eb244 -[PPRowBasedTableViewSection tableView:didSelectRowAtIndexPath:] + 175
[ERROR] :  13  Ecoline Wash                        0x00000001097eb967 -[PPSectionBasedTableViewDelegate tableView:didSelectRowAtIndexPath:] + 170
[ERROR] :  14  UIKit                               0x000000010d354e89 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1813
[ERROR] :  15  UIKit                               0x000000010d3550a4 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 344
[ERROR] :  16  UIKit                               0x000000010d2214b3 _runAfterCACommitDeferredBlocks + 318
[ERROR] :  17  UIKit                               0x000000010d21071e _cleanUpAfterCAFlushAndRunDeferredBlocks + 388
[ERROR] :  18  UIKit                               0x000000010d23eea5 _afterCACommitHandler + 137
[ERROR] :  19  CoreFoundation                      0x0000000111e79607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
[ERROR] :  20  CoreFoundation                      0x0000000111e7955e __CFRunLoopDoObservers + 430
[ERROR] :  21  CoreFoundation                      0x0000000111e5db81 __CFRunLoopRun + 1537
[ERROR] :  22  CoreFoundation                      0x0000000111e5d30b CFRunLoopRunSpecific + 635
[ERROR] :  23  GraphicsServices                    0x0000000113da2a73 GSEventRunModal + 62
[ERROR] :  24  UIKit                               0x000000010d216057 UIApplicationMain + 159
[ERROR] :  25  Ecoline Wash                        0x00000001090e0474 main + 100
[ERROR] :  26  libdyld.dylib                       0x0000000114da6955 start + 1
[LiveView] Client disconnected

**Comment by hansemannn** [comment]
Sorry, I cannot test this right now. If you need support for this, you can either check on the community or consult vendor support via mail.
